name: CI

on: push

jobs:
  install:
    name: Install Tools

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v1

      - name: help
        run: ./InitUbuntu.sh -h
      - name: basic
        run: ./InitUbuntu.sh -b
      - name: terminal
        run: ./InitUbuntu.sh terminal

      - name: common
        run: ./InitUbuntu.sh common
      - name: python
        run: ./InitUbuntu.sh python
      - name: java
        run: ./InitUbuntu.sh java
      - name: javascript
        run: ./InitUbuntu.sh javascript
      - name: docker
        run: ./InitUbuntu.sh docker
